name = "menadd"
compatibility_date = "2026-07-09"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "SUBSCRIBERS"
id = "af74c0abcbea4bf2b2afaab25308aaec"
preview_id = "d4187f9778c6416facc8982a89deedf8"
